# **Preparations for Meeting Simulation**

In [ ]:
import numpy as np
import pandas as pd

import json

from multiprocessing.pool import Pool, ThreadPool
from multiprocessing import Lock

from tqdm.notebook import trange

import copy

import sumolib

In [2]:
SEEDS = [42, 1234, 1867, 613, 1001, 704, 882, 405, 269, 120]
TIME_LIMIT = 300

In [3]:
RESULTS_ROOT = "../../02_data/01_simulation_results/"
VEH_LIST_PATH = "../../02_data/veh_list.json"
MEETING_PATH = "../../02_data/03_meeting_data/"
MEETING_VEHICLES = "../../02_data/meeting_vehicles"
EDGE_MAP_PATH = "../../02_data/edge_maps.json"
NEIGHBORING_EDGES_FILE = "../../02_data/neighboring_edges.json"

In [4]:
#reading *test* vehicles:

with open(VEH_LIST_PATH) as f:
    veh_list  = json.load(f)

test_vehicles = veh_list["test_vehs"]

## Creating the combination dataset

In [5]:
import xml.etree.ElementTree as ET

def get_relspeed_df(seed):
    tree = ET.parse(f"{RESULTS_ROOT}/edge{seed}.xml")
    root = tree.getroot()

    times = []
    edge_ids = []
    speeds = []

    for interval in root.findall("interval"):
        time = interval.get("begin")
        for edge in interval.findall("edge"):
            e_id = edge.get("id")
            rs = edge.get("speedRelative")
            if not(rs is None):
                times.append(time)
                edge_ids.append(e_id)
                speeds.append(rs)

    rs_df = pd.DataFrame()
    rs_df["time"] = times
    rs_df["edge_id"] = edge_ids
    rs_df["rel_speed"] = speeds
    
    rs_df["time"] = rs_df["time"].astype(float)
    rs_df["rel_speed"] = rs_df["rel_speed"].astype(float)
    rs_df.set_index(keys=["time", "edge_id"], inplace=True)
    
    return rs_df

In [66]:
rs_df = get_relspeed_df(42)

In [67]:
rs_df

                       rel_speed
time    edge_id
0.0     9778188#0           0.77
60.0    -1091897424#0       0.89
        -1091897424#3       0.66
        -143866037#2        0.84
        -143866037#3        0.85
...                          ...
15060.0 E9                  0.06
        E93                 0.92
        E96                 0.77
        E97                 0.97
        E98                 0.60

[185358 rows x 1 columns]

In [68]:
rs_df.loc[(60.0, "-143866037#3")].rel_speed

0.85

In [23]:
positions = pd.read_csv(f"{RESULTS_ROOT}/vehicle_positions_42.csv")

/tmp/ipykernel_4246/1478081435.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  positions = pd.read_csv(f"{RESULTS_ROOT}/vehicle_positions_42.csv")

In [33]:
positions = positions[positions["time"] != "time"]
positions["edge"] = positions["edge"].astype(str)
positions["time"] = positions["time"].astype(float)

/tmp/ipykernel_4246/2759212529.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  positions["edge"] = positions["edge"].astype(str)
/tmp/ipykernel_4246/2759212529.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  positions["time"] = positions["time"].astype(float)

In [34]:
positions = positions[~positions["edge"].str.startswith(":")]

In [35]:
positions["time_min"] = positions["time"] - positions["time"]%60
positions

             veh_id     time          edge  time_min
0              0_10     81.0  1053699407#2      60.0
1              0_10     82.0  1053699407#2      60.0
2              0_10     83.0  1053699407#2      60.0
3              0_10     84.0  1053699407#2      60.0
4              0_10     85.0  1053699407#2      60.0
...             ...      ...           ...       ...
4159605  13500_1378  15120.0   761258976#1   15120.0
4159606  13500_1431  15120.0    41384877#2   15120.0
4159607   14400_960  15120.0   506014401#1   15120.0
4159608   13500_534  15120.0           E93   15120.0
4159610   14400_409  15120.0  1233516197#1   15120.0

[3809468 rows x 4 columns]

In [42]:
rel_speeds = []
seeds = []
veh_ids = []
meas_times = []
meas_edges = []
    
for seed in SEEDS:
    positions = pd.read_csv(f"{RESULTS_ROOT}/vehicle_positions_{seed}.csv")
    positions = positions[positions["time"] != "time"]
    positions["time"] = positions["time"].astype(float)
    positions["edge"] = positions["edge"].astype(str)
    positions = positions[~positions["edge"].str.startswith(":")]
    positions["time_min"] = positions["time"] - positions["time"]%60
    
    rel_speed_df = get_relspeed_df(seed)
    
    for veh in test_vehicles:
        veh_movement = positions[positions["veh_id"] == veh]
        meas_vals = []
        meas_time = []
        meas_edge = []
        for _,r in veh_movement.iterrows():
            if (r.time_min, r.edge) in rel_speed_df.index:
                meas_vals.append(rel_speed_df.loc[(r.time_min, r.edge)].rel_speed)
                meas_time.append(r.time_min)
                meas_edge.append(r.edge)
    
        rel_speeds += meas_vals
        seeds += [seed]*len(meas_vals)
        veh_ids += [veh]*len(meas_vals)
        meas_times += meas_time
        meas_edges += meas_edge

/tmp/ipykernel_9062/797137283.py:8: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  positions = pd.read_csv(f"{RESULTS_ROOT}/vehicle_positions_{seed}.csv")
/tmp/ipykernel_9062/797137283.py:8: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  positions = pd.read_csv(f"{RESULTS_ROOT}/vehicle_positions_{seed}.csv")
/tmp/ipykernel_9062/797137283.py:8: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  positions = pd.read_csv(f"{RESULTS_ROOT}/vehicle_positions_{seed}.csv")
/tmp/ipykernel_9062/797137283.py:8: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  positions = pd.read_csv(f"{RESULTS_ROOT}/vehicle_positions_{seed}.csv")
/tmp/ipykernel_9062/797137283.py:8: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  positions = pd.read_csv(f"{RESULTS_ROOT}/vehicle_positions_{seed}.csv")
/tmp/ipykernel_9062/797137283.py:8: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  positions = pd.read_csv(f"{RESULTS_ROOT}/vehicle_positions_{seed}.csv")
/tmp/ipykernel_9062/797137283.py:8: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  positions = pd.read_csv(f"{RESULTS_ROOT}/vehicle_positions_{seed}.csv")
/tmp/ipykernel_9062/797137283.py:8: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  positions = pd.read_csv(f"{RESULTS_ROOT}/vehicle_positions_{seed}.csv")
/tmp/ipykernel_9062/797137283.py:8: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  positions = pd.read_csv(f"{RESULTS_ROOT}/vehicle_positions_{seed}.csv")
/tmp/ipykernel_9062/797137283.py:8: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  positions = pd.read_csv(f"{RESULTS_ROOT}/vehicle_positions_{seed}.csv")

In [43]:
combined_df = pd.DataFrame()
combined_df["time"] = meas_times
combined_df["veh_id"] = veh_ids
combined_df["edge"] = meas_edges
combined_df["rel_speed"] = rel_speeds
combined_df["seed"] = seeds

In [44]:
combined_df

            time     veh_id        edge  rel_speed  seed
0         3540.0  2700_1115          E7       0.80    42
1         3540.0  2700_1115          E7       0.80    42
2         3540.0  2700_1115          E7       0.80    42
3         3540.0  2700_1115          E7       0.80    42
4         3540.0  2700_1115          E7       0.80    42
...          ...        ...         ...        ...   ...
10452597  1620.0    900_181  13639604#1       0.92   120
10452598  1620.0    900_181  13639604#1       0.92   120
10452599  1620.0    900_181  13639604#1       0.92   120
10452600  1620.0    900_181  13639604#2       0.87   120
10452601  1620.0    900_181  13639604#2       0.87   120

[10452602 rows x 5 columns]

In [45]:
#creating key for the measurements:

def calculate_hash(datarow):
    key = datarow.edge + str(datarow.time) + str(datarow.rel_speed) + str(datarow.seed)
    return hash(key)


hashes = []
for _,r in combined_df.iterrows():
    hashes.append(calculate_hash(r))
combined_df["hash"] = hashes

In [46]:
combined_df.to_csv(f"{MEETING_PATH}/combined_dataset.csv", index=False)

## Collecting neighboring edges

In [12]:
#input:
NETWORK_FILE = "../../01_simulation/02_scenario/hats.net.xml"
#output:
NEIGHBORING_EDGE_FILE = "../../02_data/neighboring_edges.json"

In [23]:
net = sumolib.net.readNet(NETWORK_FILE)
edges = net.getEdges()
neighbors = {}

#collecting neighbors:
for edge in edges:
    edge_id = edge.getID()
    neighbors[edge_id] = []
    for inc in edge.getFromNode().getIncoming():
        neighbors[edge_id].append(inc.getID())
    for outg in edge.getFromNode().getOutgoing():
        neighbors[edge_id].append(outg.getID())
    for inc in edge.getToNode().getIncoming():
        neighbors[edge_id].append(inc.getID())
    for outg in edge.getToNode().getOutgoing():
        neighbors[edge_id].append(outg.getID())    
        
#a couple of edges are connected to each other,
#therefore, we have to remove them from it neighbors:
for edge in neighbors:
    if edge in neighbors[edge]:
        neighbors[edge].remove(edge)

In [24]:
with open(NEIGHBORING_EDGE_FILE, "w") as f:
    json.dump(neighbors, f)

## Collecting meeting vehicles

In [25]:
#reading *test* vehicles:
with open(VEH_LIST_PATH) as f:
    veh_list  = json.load(f)

test_vehicles = veh_list["test_vehs"]

with open(EDGE_MAP_PATH) as f:
    edge_maps = json.load(f)

edge_to_idx = edge_maps["edge_to_idx"]

with open(NEIGHBORING_EDGES_FILE) as f:
    neighbors = json.load(f)

In [26]:
#reading moving simulation data:

m_data = pd.DataFrame()
for s in SEEDS:
    filename = f"{RESULTS_ROOT}/vehicle_positions_{s}.csv"
    mf = pd.read_csv(filename)
    mf["seed"] = [s]*len(mf)
    m_data = pd.concat([m_data, mf])

In [31]:
m_data = m_data[~m_data["edge"].str.startswith(":").astype(bool)]

### Meeting definition functions

In [33]:
def collect_meeting_vehicles_narrow(m_data, meeting_time, meeting_times, meeting_time_gap=TIME_LIMIT):
    #collecting recently met vehicles:
    
    meetings = m_data[m_data["time"] == meeting_time]

    mets = []

    #same edges:
    for edge in edge_to_idx:
        vehs = meetings[meetings["edge"] == edge]["veh_id"].unique()
        for i in range(len(vehs)):
            for j in range(i+1, len(vehs)):
                sender = vehs[i]
                receiver = vehs[j]
                #if not met yet or met long time ago:
                if ((not((sender, receiver) in meeting_times)) or
                    meeting_time - meeting_times[(sender, receiver)] > meeting_time_gap):
                    mets.append((sender, receiver))
                    mets.append((receiver, sender)) #they meet vice-versa

    #opposed edges:
    for edge in edge_to_idx:
        #only "reversed" edges are processed, to avoid duplicated meetings:
        if edge.startswith("-"):
            veh_edge = meetings[meetings["edge"] == edge]["veh_id"].unique()
            contra_edge = edge.split("-")[1]
            veh_contra = meetings[meetings["edge"] == contra_edge]["veh_id"].unique()
            for sender in veh_edge:
                for receiver in veh_contra:
                    #if not met yet or met long time ago:
                    if ((not((sender, receiver) in meeting_times)) or
                        meeting_time - meeting_times[(sender, receiver)] > meeting_time_gap):
                        mets.append((sender, receiver))
                        mets.append((receiver, sender)) #they meet vice-versa


    return mets #vehicles at the same time, at the same place, not the 'ego' vehicle and not met recently

In [34]:
def collect_meeting_vehicles_broad(m_data, meeting_time, meeting_times, meeting_time_gap=TIME_LIMIT,
                                   neighboring_edges = neighbors):
    #collecting recently met vehicles:
    
    meetings = m_data[m_data["time"] == meeting_time]

    mets = []
        
    for edge in edge_to_idx:
        veh_edge = meetings[meetings["edge"] == edge]["veh_id"].unique()
        #same edge:
        for i in range(len(veh_edge)):
            for j in range(i+1, len(veh_edge)):
                sender = veh_edge[i]
                receiver = veh_edge[j]
                #if not met yet or met long time ago:
                if ((not((sender, receiver) in meeting_times)) or
                    meeting_time - meeting_times[(sender, receiver)] > meeting_time_gap):
                    mets.append((sender, receiver))
                    mets.append((receiver, sender)) #they meet vice-versa
        
        #neighboring edges:
        veh_contra = meetings[meetings["edge"].isin(neighboring_edges[edge])]["veh_id"].unique()
        for sender in veh_edge:
            for receiver in veh_contra:
                #if not met yet or met long time ago:
                if ((not((sender, receiver) in meeting_times)) or
                    meeting_time - meeting_times[(sender, receiver)] > meeting_time_gap):
                    mets.append((sender, receiver)) #vice-versa meetings are coming from the other neighboring


    return mets #vehicles at the same time, at the same place, not the 'ego' vehicle and not met recently

In [35]:
#running the collector scripts:
def collector_script(args):
    seed, collect_method, meas_name = args
    meeting_times = {}
    meeting_collection = {}

    m_data_filt = m_data[m_data["seed"] == seed]
    m_data_hour = m_data_filt[m_data_filt["time"] <= min(m_data_filt["time"])+6*60*60]
    
    for t in range(int(min(m_data["time"])), int(max(m_data["time"]))):
        if t%(6*60*60) == 0:
            m_data_hour = m_data_filt[(m_data_filt["time"] >= t) &
                            (m_data_filt["time"] < t+6*60*60)]
        #m_data_filt = m_data_filt[m_data_filt["time"] >= t]
        meetings = collect_method(m_data_hour, t, meeting_times)
        meeting_collection[t] = meetings
        for sender, receiver in meetings:
            meeting_times[(sender, receiver)] = t

    with open(f"{MEETING_VEHICLES}_{meas_name}_{seed}.json", "w") as f:
        json.dump(meeting_collection, f)

In [50]:
m_data = m_data[~(m_data["time"] == "time")]
m_data["time"] = m_data["time"].astype(float)

### Parallel running:

In [51]:
with Pool(5) as ps:
    #for broad measurements:
    ps.map(collector_script, zip(SEEDS, [collect_meeting_vehicles_broad]*10, ["broad"]*10))
    #for narrow measurements:
    #ps.map(collector_script, zip(SEEDS, [collect_meeting_vehicles_narrow]*5, ["narrow"]*5))